### ISSUE TITLE
连接超时，各种配置也配了，不确定为什么

### ISSUE THREAD

**Issue by hixiu** [holll/teledown#7]
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError:

**Comment by holll** [comment]
前面那个Cannot find reference 'SOCKS5' in 'socks.py'是解决了吗？

**Comment by herman6b6** [comment]
我也遇到这问题了，请问有解决方法吗？之前成功过，后面就不行了.....

Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: TimeoutError: 
Attempt 6 at connecting failed: TimeoutError: 
Traceback (most recent call last):
  File "C:\Users\PVE\IdeaProjects\teledown\main.py", line 106, in <module>
    with client.start(phone=phone, bot_token=bot_token):
         ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\site-packages\telethon\client\auth.py", line 128, in start
    else self.loop.run_until_complete(coro)
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Program Files\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Program Files\Python313\Lib\site-packages\telethon\client\auth.py", line 135, in _start
    await self.connect()
  File "C:\Program Files\Python313\Lib\site-packages\telethon\client\telegrambaseclient.py", line 548, in connect
    if not await self._sender.connect(self._connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )):
    ^^
  File "C:\Program Files\Python313\Lib\site-packages\telethon\network\mtprotosender.py", line 134, in connect
    await self._connect()
  File "C:\Program Files\Python313\Lib\site-packages\telethon\network\mtprotosender.py", line 260, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)

Process finished with exit code 1

**Comment by holll** [comment]
> 我也遇到这问题了，请问有解决方法吗？之前成功过，后面就不行了.....
> 
> Attempt 1 at connecting failed: TimeoutError: Attempt 2 at connecting failed: TimeoutError: Attempt 3 at connecting failed: TimeoutError: Attempt 4 at connecting failed: TimeoutError: Attempt 5 at connecting failed: TimeoutError: Attempt 6 at connecting failed: TimeoutError: Traceback (most recent call last): File "C:\Users\PVE\IdeaProjects\teledown\main.py", line 106, in with client.start(phone=phone, bot_token=bot_token): ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python313\Lib\site-packages\telethon\client\auth.py", line 128, in start else self.loop.run_until_complete(coro) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^ File "C:\Program Files\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete return future.result() ~~~~~~~~~~~~~^^ File "C:\Program Files\Python313\Lib\site-packages\telethon\client\auth.py", line 135, in _start await self.connect() File "C:\Program Files\Python313\Lib\site-packages\telethon\client\telegrambaseclient.py", line 548, in connect if not await self._sender.connect(self._connection( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...<6 lines>... )): ^^ File "C:\Program Files\Python313\Lib\site-packages\telethon\network\mtprotosender.py", line 134, in connect await self._connect() File "C:\Program Files\Python313\Lib\site-packages\telethon\network\mtprotosender.py", line 260, in _connect raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries)) ConnectionError: Connection to Telegram failed 5 time(s)
> 
> Process finished with exit code 1

TCPPING对应端口，看看是不是被墙了，sock5协议就是裸连，很容易被墙

**Comment by herman6b6** [comment]
已经解决了，应该不是被墙，是之前已经用过该设备认证过，删掉了session后，重新执行-re无法重新调起认证，我是用其他设备在setting里面删除掉之前的session设备后就能重新发起认证 。
